### PR TITLE
Add Alias Model/API

### LINKED ISSUE #31: BACKEND: Add an Alias Table/API to Keep the Different Versions for a Tag
Samples:  

- `hack-for-la` ,  `hackforla` ,  `hack4la`,  `hack-4-la`
- `code-for-america`  ,  `codeforamerica`  ,  `code-4-america` ,  `code4america `
-  `civictechindex` ,  `civic-tech-index`

### PR DESCRIPTION
**Pull request by emecas**
General Steps:

   1. Adding Model `Alias` under: `civictechindexadmin/data/models.py`
   2. Adding admin class `AliasAdmin` under `civictechindexadmin/data/admin.py`
   3. Adding Serializer `AliasSerializer` under: `civictechindexadmin/data/api/serializers.py`
   4. Adding View `AliasViewSet` under: `civictechindexadmin/data/api/views.py`
   5. Registering API router at `config/api_router.py`
   6. Making migrations

close #31

### CODE REVIEW

**Comment by cnk** [comment]
Generally looks good. Please delete the two unrelated migration files (the one for sites and the one for users) and then I'll finish the review.

**Review by cnk — APPROVED** [review]
Looks fine to me

**Comment by giosce** [comment]
My understanding is that aliases are for Organizations. As such, I was thinking to have a list of aliases as attribute of Organization. In that case I don't think we need the API and instead we need to make Alias child of Organization.
@emecas can you please verify the use case for aliases?

**Comment by emecas** [comment]
Gio, Alias API is an independent functionality for what we defined about having a way to look up/translate equivalent  tags, during our Sunday meeting a couple weeks ago. Also you could see the idea in the examples I’ve provided in #31.

A particular tag can be an organization as well as A topic,  and it is not tied to any single screen, APU can be used by the tag generator, search screen, or any other screens when you need to translate the input from the user to the standard representation of CTI.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cnk** [comment]
@giosce @emecas The Alias API has been deployed to https://test-civictechindexadmin.herokuapp.com/swagger/

**Pull request merged**
