### PR TITLE
Update Settings - This should resolve, #1049

### PR DESCRIPTION
**Pull request by deserat**
I just set `USE_X_FORWARDED_FOR` to  True. This will resolve this issue for most proxy servers. 

This cannnot be tested locally and will require support from Ops.

### CODE REVIEW

**Comment by cnk** [comment]
Can you please add a link to the documents for how Django would use USE_X_FORWARDED_FOR? I am not seeing it on https://docs.djangoproject.com/en/3.2/ref/settings/

And my guess for where the fix for #1049 would be is in the server configuration rather than the django settings file.

**Comment by deserat** [comment]
My bad. Sorry I was tired and not thinking. Will push a new commit in the next couple of days.

**Comment by deserat** [comment]
Updated Code.

**X_FORWARDED_FOR**

Install `django-xff` middleware and configure it.  https://pypi.org/project/django-xff/

There are a few middlewares that accomplish the same thing. All set `request.META['REMOTE_ADDR'] to the client ip. This one seemed to be the most well thought out.

The middleware itself provides some security features which I don't know that we need so I left them commented out with an explanation at the bottom of settings.py, in case we desire to take advantage of them. 

**.gitignore**

Ignore `.idea` directory. I'm following the convention which already exists in the .gitignore of ignoring Editor configs.

**Tests**

There are no logic changes to the existing code only the addition of middleware. All existing tests pass.

**Extraneous**

I'm not sure why the github PR is showing a diff on files that have already been merged into `main` like the README. Caching maybe?

**Review by cnk — APPROVED** [review]
Looks reasonable but as @deserat mentions, we will need to deploy this to find out. Perhaps you can get on the agenda for this week's ops meeting and deploy

**Pull request merged**
