### PR TITLE
First version of the script to check the URL from the Link database t…

### PR DESCRIPTION
**Pull request by giosce**
First version of the script to check all the URL from the Link database table. Run it as ./manage.py links_checker 
It records check results in /code/links_checker.log file.

### CODE REVIEW

**Comment by giosce** [comment]
I think functionally this change is now complete. I wil l take a look into codeclimate issues, but I'd love for the change to be deployed.

**Comment by giosce** [comment]
I realized I need to handle the case in which a link is broken (or 400) and then it is fixed.

**Comment by giosce** [comment]
Added handling of URL becoming a valid one.
Please, review, let me know if something needs to be fixed and so we can merge and finish to test this functionality.

**Comment by cnk** [comment]
@giosce Sorry it took so long for me to sit down and review this. There were a lot of small changes that needed to be made to clean up this code and make it more Pythonic. I don't see how to push those changes here so I opened a pull request against your repository. If you are OK with my changes, you can merge that PR into your 'main' and then push those changes to this PR for Code Climate run and a merge.

**Pull request merged**
